### ISSUE TITLE
How about to remove word Agent from some parts of this repo?

### ISSUE THREAD

**Issue by sbrin** [NirDiamant/GenAI_Agents#4]
How about to remove the word Agent from some parts in this repo?

It is misleading. It is so wrong to call API wrappers "the agents"

According to definition:

> an intelligent agent is an agent that perceives its environment, takes actions autonomously in order to achieve goals, and may improve its performance with learning or acquiring knowledge

I can't see any autonomous traits in conversational agents. 

Non of the first 10 in this list can act autonomously, have goals or may improve.

Although I appreciate this initiative and grateful for all the work done to manage such a good collection

**Comment by NirDiamant** [comment]
Hi :) and thanks for the input. 
As the purpose is to let people know how to create agents, we need to start from some basics.
